import eslintPluginSvelte from "eslint-plugin-svelte";
import eslintParserSvelte from "svelte-eslint-parser";

export default {
	name: "@klnjs/svelte",
	files: ["**/*.svelte"],
	processor: "svelte/svelte",
	plugins: {
		svelte: eslintPluginSvelte,
	},
	languageOptions: {
		parser: eslintParserSvelte,
	},
	rules: {
		// The following builtin rules have a Svelte extension rule.
		// See: https://github.com/sveltejs/eslint-plugin-svelte?tab=readme-ov-file#extension-rules
		"no-inner-declarations": "off", // The AST generated by svelte-eslint-parser will false positives in it rule because the root node of the script is not the `Program`.
		"no-self-assign": "off",

		// The following configures all svelte-eslint-plugin rules.
		// See: https://typescript-eslint.io/rules
	},
};
