import rPlugin from 'eslint-plugin-react'

export const plugin = rPlugin

export const prefix = 'react'

export const getRules = () => ({
	[`${prefix}/boolean-prop-naming`]: 'off',
	[`${prefix}/button-has-type`]: 'off',
	[`${prefix}/default-props-match-prop-types`]: 'off',
	[`${prefix}/destructuring-assignment`]: 'off',
	[`${prefix}/display-name`]: 'off',
	[`${prefix}/forbid-component-props`]: 'off',
	[`${prefix}/forbid-dom-props`]: 'off',
	[`${prefix}/forbid-elements`]: 'off',
	[`${prefix}/forbid-foreign-prop-types`]: 'error',
	[`${prefix}/forbid-prop-types`]: 'off',
	[`${prefix}/function-component-definition`]: 'off',
	[`${prefix}/hook-use-state`]: 'error',
	[`${prefix}/iframe-missing-sandbox`]: 'off',
	[`${prefix}/jsx-boolean-value`]: 'off',
	[`${prefix}/jsx-child-element-spacing`]: 'off',
	[`${prefix}/jsx-closing-bracket-location`]: 'off',
	[`${prefix}/jsx-closing-tag-location`]: 'off',
	[`${prefix}/jsx-curly-brace-presence`]: [
		'error',
		{ props: 'never', children: 'never' }
	],
	[`${prefix}/jsx-curly-spacing`]: 'off',
	[`${prefix}/jsx-equals-spacing`]: 'off',
	[`${prefix}/jsx-filename-extension`]: [
		'error',
		{ extensions: ['.jsx', '.tsx'] }
	],
	[`${prefix}/jsx-first-prop-new-line`]: 'off',
	[`${prefix}/jsx-fragments`]: ['error', 'syntax'],
	[`${prefix}/jsx-handler-names`]: 'off',
	[`${prefix}/jsx-indent-props`]: 'off',
	[`${prefix}/jsx-indent`]: 'off',
	[`${prefix}/jsx-key`]: 'off',
	[`${prefix}/jsx-max-depth`]: 'off',
	[`${prefix}/jsx-max-props-per-line`]: 'off',
	[`${prefix}/jsx-newline`]: 'off',
	[`${prefix}/jsx-no-bind`]: [
		'error',
		{
			ignoreRefs: true,
			allowArrowFunctions: true,
			allowFunctions: false,
			allowBind: false,
			ignoreDOMComponents: true
		}
	],
	[`${prefix}/jsx-no-comment-textnodes`]: 'error',
	[`${prefix}/jsx-no-constructed-context-values`]: 'error',
	[`${prefix}/jsx-no-duplicate-props`]: ['error', { ignoreCase: true }],
	[`${prefix}/jsx-no-leaked-render`]: 'error',
	[`${prefix}/jsx-no-literals`]: 'off',
	[`${prefix}/jsx-no-script-url`]: 'error',
	[`${prefix}/jsx-no-target-blank`]: [
		'error',
		{ enforceDynamicLinks: 'always' }
	],
	[`${prefix}/jsx-no-undef`]: 'error',
	[`${prefix}/jsx-no-useless-fragment`]: 'error',
	[`${prefix}/jsx-one-expression-per-line`]: 'off',
	[`${prefix}/jsx-pascal-case`]: [
		'error',
		{ allowAllCaps: true, ignore: [] }
	],
	[`${prefix}/jsx-props-no-multi-spaces`]: 'off',
	[`${prefix}/jsx-props-no-spreading`]: 'off',
	[`${prefix}/jsx-sort-props`]: 'off',
	[`${prefix}/jsx-tag-spacing`]: 'off',
	[`${prefix}/jsx-uses-react`]: 'off',
	[`${prefix}/jsx-uses-vars`]: 'error',
	[`${prefix}/jsx-wrap-multilines`]: 'off',
	[`${prefix}/no-access-state-in-setstate`]: 'error',
	[`${prefix}/no-adjacent-inline-elements`]: 'off',
	[`${prefix}/no-array-index-key`]: 'error',
	[`${prefix}/no-arrow-function-lifecycle`]: 'error',
	[`${prefix}/no-children-prop`]: 'off',
	[`${prefix}/no-danger-with-children`]: 'error',
	[`${prefix}/no-danger`]: 'warn',
	[`${prefix}/no-deprecated`]: 'error',
	[`${prefix}/no-did-mount-set-state`]: 'off',
	[`${prefix}/no-did-update-set-state`]: 'error',
	[`${prefix}/no-direct-mutation-state`]: 'off',
	[`${prefix}/no-find-dom-node`]: 'error',
	[`${prefix}/no-invalid-html-attribute`]: 'error',
	[`${prefix}/no-is-mounted`]: 'error',
	[`${prefix}/no-multi-comp`]: 'off',
	[`${prefix}/no-namespace`]: 'error',
	[`${prefix}/no-object-type-as-default-prop`]: 'error',
	[`${prefix}/no-redundant-should-component-update`]: 'error',
	[`${prefix}/no-render-return-value`]: 'error',
	[`${prefix}/no-set-state`]: 'off',
	[`${prefix}/no-string-refs`]: 'error',
	[`${prefix}/no-this-in-sfc`]: 'error',
	[`${prefix}/no-typos`]: 'error',
	[`${prefix}/no-unescaped-entities`]: 'error',
	[`${prefix}/no-unknown-property`]: 'error',
	[`${prefix}/no-unsafe`]: 'off',
	[`${prefix}/no-unstable-nested-components`]: 'error',
	[`${prefix}/no-unused-class-component-methods`]: 'error',
	[`${prefix}/no-unused-prop-types`]: 'error',
	[`${prefix}/no-unused-state`]: 'error',
	[`${prefix}/no-will-update-set-state`]: 'error',
	[`${prefix}/prefer-es6-class`]: 'error',
	[`${prefix}/prefer-exact-props`]: 'error',
	[`${prefix}/prefer-read-only-props`]: 'off',
	[`${prefix}/prefer-stateless-function`]: 'off',
	[`${prefix}/prop-types`]: 'error',
	[`${prefix}/react-in-jsx-scope`]: 'off',
	[`${prefix}/require-default-props`]: 'off',
	[`${prefix}/require-optimization`]: 'off',
	[`${prefix}/require-render-return`]: 'error',
	[`${prefix}/self-closing-comp`]: 'error',
	[`${prefix}/sort-comp`]: 'off',
	[`${prefix}/sort-default-props`]: 'off',
	[`${prefix}/sort-prop-types`]: 'off',
	[`${prefix}/state-in-constructor`]: 'off',
	[`${prefix}/static-property-placement`]: 'off',
	[`${prefix}/style-prop-object`]: 'error',
	[`${prefix}/void-dom-elements-no-children`]: 'error'
})
